location __PATH__/ {
    proxy_pass http://127.0.0.1:__PORT__/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

# git-nostr-bridge HTTP API/git-over-HTTPS, if you expose it
location __PATH__/git/ {
    proxy_pass http://127.0.0.1:__BRIDGE_HTTP_PORT__/;
    client_max_body_size 500M;
}
